configs:
    - configs/exps/vggt/experimental/vggt_v2.yaml

model_cfg:
    sampler_cfg:
        # Finetune from the pretrained VGGT model
        load_pretrained: True
        dinov2_ckpt: /horizon-bucket/saturn_v_dev/01_users/tao02.xie/projects/GFM/gfm/data/trained_model/dinov2/backbones/dinov2_vitl14_reg4_pretrain.pth
        agg_regator_ckpt: /horizon-bucket/saturn_v_dev/01_users/tao02.xie/projects/GFM/gfm/data/trained_model/vggt/official/VGGT-1B/aggregator.pt
        cam_decoder_ckpt: /horizon-bucket/saturn_v_dev/01_users/tao02.xie/projects/GFM/gfm/data/trained_model/vggt/official/VGGT-1B/camera.pt
        xyz_decoder_ckpt: /horizon-bucket/saturn_v_dev/01_users/tao02.xie/projects/GFM/gfm/data/trained_model/vggt/official/VGGT-1B/point.pt
        dpt_decoder_ckpt: /horizon-bucket/saturn_v_dev/01_users/tao02.xie/projects/GFM/gfm/data/trained_model/vggt/official/VGGT-1B/depth.pt
        tra_decoder_ckpt: /horizon-bucket/saturn_v_dev/01_users/tao02.xie/projects/GFM/gfm/data/trained_model/vggt/official/VGGT-1B/track.pt
        # Use camera token
        cam_emb_dropout: 0.1
        use_cam_emb: True
        use_cam_token: True
        cam_embed_cfg:
            type: CameraCondition
            out_features: 1024
            use_modulation: True
            use_gate: True
            use_transformer: True
            use_checkpoint: True

dataloader_cfg:
    dataset_cfg:  # config of class GeneralizableDataset
        _delete_: True
        type: GeneralizableDataset
        split: TRAIN
        runtime_build: True
        delete_after_runtime_build: True
        global_sharding: True
        dataset_indexing: True
        n_frames_batch: 24
        parallel_loading: True
        dataloading_workers: 64
        meta_file: /horizon-bucket/saturn_v_4dlabel/008_Simulation/001_users/xiaoyang.guo/data/gfm_v1_dl3dv.pkl
        meta_roots:
            # Synthetic datasets
            - /horizon-bucket/saturn_v_dev/users/tao02.xie/datasets/hypersim/train
            - /horizon-bucket/saturn_v_dev/users/tao02.xie/datasets/hypersim/val
            - /horizon-bucket/saturn_v_dev/users/tao02.xie/datasets/mvs_synth/GTAV_1080
            - /horizon-bucket/saturn_v_dev/users/tao02.xie/datasets/vkitti2
            # Real-world datasets
            - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/tao02.xie/datasets/mapfree/train
            - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/tao02.xie/datasets/mapillary/train
            # - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/tao02.xie/datasets/mapillary/val
        metaset_cfgs:  # configs for each dataset, the last one is the default config
            # The unified ratio is only used for a placeholder
            # The actual resolution is determined by the max_size, lazy resizing
            # Synthetic datasets
            - dataset_name: "hypersim/train"  # 613 high-quality synthetic scenes
              max_depth_quantile: 0.99
              prob: 1.0
            - dataset_name: "hypersim/val"  # 77 high-quality synthetic scenes
              max_depth_quantile: 0.99
              prob: 1.0
            - dataset_name: "GTAV_1080"  # 120 game scenes
              min_depth_quantile: 0.0
              max_depth_quantile: 0.95
              ims_pattern: '{frame:06d}.png'
              prob: 1.0
            - dataset_name: "vkitti2"  # 50 synthetic driving scenes
              interp_using_t: True
              closest_using_t: True
              max_depth: 200 # meter unit, remove the sky
              min_depth_quantile: 0.0
              max_depth_quantile: 0.98
              ims_pattern: '{frame:05d}.jpg'
              mks_pattern: '{frame:05d}.png'
              dps_pattern: '{frame:05d}.exr'
              prob: 1.0
            # Real-world datasets
            - dataset_name: "mapfree/train"  # 918 scenes
              min_depth_quantile: 0.02
              max_depth_quantile: 0.95
              use_masks: True
              masks_dir: masks
              prob: 1.0
            - dataset_name: "mapillary/train"  # 74 driving scenes
              min_depth_quantile: 0.02
              max_depth_quantile: 0.95
              interp_using_t: True
              closest_using_t: True
              prob: 1.0
            # - dataset_name: "mapillary/val"  # 36 driving scenes
            #   ratio: 1.0
            #   min_depth_quantile: 0.02
            #   max_depth_quantile: 0.95
            #   dist_opt_K: True
            #   interp_using_t: True
            #   closest_using_t: True
            #   prob: 0.25
            - type: VGGTDataset  # NOTE this is the default config
              ddp_shard_dataset: False
              n_rays: -1
              max_size: 518 # use this to resize the image
              align_size: 14 # align the image to this size
              disk_dataset: True # to avoid loading all data into memory
              dist_opt_K: False # no distortion for synthetic data
              use_depths: True # use ground truth depths
              use_vhulls: False
              view_sample: [0, null, 1]
              frame_sample: [0, null, 1]
              source_type: DISTANCEROT
              extra_src_pool: 24 # expand the source pool to twice the number of sources
              min_depth_quantile: 0.0
              max_depth_quantile: 1.0
              scale_type: DIST
              portrait_check: False
              center_crop: True # retrain the original fx and fy
              limit_max_aspect_ratio_as_original_ratio: True # limit the maximum aspect ratio as the original image ratio
              aug_scale: 0.3 # fov augmentation
              aug_image: True # image augmentation
              aug_image_cojit: True
              aug_image_cojit_ratio: 0.3 # 30% of the time, use individual image augmentation for each source
              n_srcs_list: &train_n_srcs_list [
                  1,
                  2,
                  3,
                  4,
                  5,
                  6,
                  7,
                  8,
                  9,
                  10,
                  11,
                  12,
                  13,
                  14,
                  15,
                  16,
                  17,
                  18,
                  19,
                  20,
                  21,
                  22,
                  23
              ]
              n_srcs_prob: &train_n_srcs_probs [
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0
              ]
