# ft业务行车数据 ablation结论 https://horizonrobotics.feishu.cn/wiki/Vm9IwO7iVivRCNkk6bjc5APCnHd#K311dPP8LodtYtxCfeZcRaeUnqf
# 1. pose-weight x5：pose-auc-01提升一个点左右，depth无影响；
# 2. aug：增加aug对pose和depth均有提升；当前v4版本收益待确认；
# 3. scaleup x4：pose-auc-01提升2.2个点，depth提升4.3个点；还能进一步scaleup；
# 4. lr：2x8卡 lr设为1e-5，相较于5e-6 pose-auc-01提升1.4个点，depth提升2个点；
# 5. vggtbatchsampler：影响不大，pose（translation）有略微收敛加速，depth基本无变化；

# 收敛性质：
# 1. 默认2x8卡，lr from 2e-5 to 1e-8，160k step：depth在100k左右停止收敛，pose在130k左右停止收敛；

# 训练启动脚本
# python aidi/submit.py --job_name bussiness_stage2_basemodel --cluster_name project-a800-4dlabel-perception2-bcloud --gpu 8 --node 8 --priority 4 'aidi/run.sh --config vggt/saturnv/base/vggt_mvsseq --exp_name exp/basemodel/1003/8x8_1e-4_stage2_resumebase --train --train_args "runner_cfg.resume=True model_cfg.sampler_cfg.load_pretrained=True model_cfg.supervisor_cfg.pose_loss_type=L1 runner_cfg.train_use_amp=True model_cfg.sampler_cfg.use_checkpoint=True " --multi_machine --dist'

# Configuration for VGGT
configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/vggt.yaml # network model configuration
    - configs/models/vggt_sample.yaml

# FSDP: https://docs.pytorch.org/tutorials/intermediate/FSDP_tutorial.html
fsdp_enabled: False
runner_cfg:
    gradient_accumulation_steps: 2
    fsdp_shard_class_list: ['NestedTensorBlock', 'Block', 'DPTHead', 'CameraHead']
    test_with_ddp_sharding: &test_with_ddp_sharding True

    visualizer_cfg:
        type: SequentialVisualizer
        visualizer_cfgs: []
        
    evaluator_cfg:
        type: GeometryEvaluator
        compute_cam_metrics: ['CAM_ACC_AUC','CAM_EVO']
        compute_dpt_metrics: ["DPT","DPT_TARGET"]
        # compute_xyz_metrics: ['XYZ']
        fixscale: True
    
    optimizer_cfg:
        lr: 1.e-4 # default 8*8 with accumulation
        eps: 1.e-8
        weight_decay: 5.e-2
        lr_table:
            patch_embed: 2.e-5 # default 8*8 with accumulation
        optimizer_cfg:
            type: AdamW # most common in transformer models

    scheduler_cfg:
        type: WarmupCosineLR
        warmup_iters: 0  # xy: add warmup

    epochs: 160 # 160k by paper
    ep_iter: 1000
    save_latest_ep: 5  # xy: less to save time
    save_ep: 5  # xy: less to save time
    eval_ep: 5  # xy: less to save time
    log_interval: 50
    test_before_first_epoch: True
    empty_cache_ep: 1 # eval_ep
    

model_cfg:
    supervisor_cfg:
        supervisor_cfgs:
            - type: PoseSupervisor
            - type: DepthSupervisor

    sampler_cfg:
        vggt_batching: False # use the custom VGGT batching
        load_pretrained: False
        use_cam_emb: True  # use camera embedding
        # freeze_list: ["agg_regator", "xyz_decoder", "dpt_decoder"]  # for debug
        use_3ddr: True
        use_xyz_head: False

        # vitsmall
        dinov2_ckpt: /horizon-bucket/saturn_v_dev/01_users/tao02.xie/projects/GFM/gfm/data/trained_model/dinov2/backbones/dinov2_vits14_reg4_pretrain.pth
        agg_regator_cfg:
            patch_embed: dinov2_vits14_reg
            img_size: 518
            patch_size: 14
            embed_dim: &embed_dim 384
            intermediate_layer_idx: &intermediate_layer_idx [2, 5, 8, 11]
            num_heads: 6
            depth: 12

        cam_embed_cfg:
            type: CamMlp
            in_features: 10
            hidden_features: *embed_dim
            out_features: 1536 # embed_dim*4

        cam_decoder_cfg:
            dim_in: 768 # embed_dim*2

        # xyz_decoder_cfg:
        #     dim_in: 768 # embed_dim*2
        #     output_dim: 4
        #     activation: inv_log
        #     conf_activation: expp1
        #     intermediate_layer_idx: *intermediate_layer_idx

        dpt_decoder_cfg:
            dim_in: 768 # embed_dim*2
            output_dim: 2
            activation: exp
            conf_activation: expp1
            intermediate_layer_idx: *intermediate_layer_idx

dataloader_cfg:
    num_workers: 16  # xy: modify num_workers here
    dataset_cfg:
        _delete_: True
        type: GeneralizableDataset
        split: TRAIN
        runtime_build: True  # modified by xiaoyang, avoid loading all data into memory
        global_sharding: True
        dataset_indexing: True
        parallel_loading: True
        dataloading_workers: 16  # TODO: not working if runtime_build is True
        delete_after_runtime_build: True
        meta_roots:
            # mechanical datasets
            - /horizon-bucket/perception-dataprocess/4dlabel/static_visual/002_vggt_data/evc_data/business_data/parking_data/20250728_mechanical_at128_train
            # mechanical fisheye datasets
            - /horizon-bucket/perception-dataprocess/4dlabel/static_visual/002_vggt_data/evc_data/business_data/parking_data/20250728_mechanical_at128_train
            # parking dataset
            - /horizon-bucket/perception-dataprocess/4dlabel/static_visual/002_vggt_data/evc_data/business_data/parking_data/20250613_train
            # driving dataset
            - /horizon-bucket/perception-dataprocess/4dlabel/static_visual/002_vggt_data/evc_data/business_data/driving_data/20250613_train
        metaset_cfgs:
            # The unified ratio is only used for a placeholder
            # The actual resolution is determined by the max_size, lazy resizing
            # Synthetic datasets
            - dataset_name: "parking_mechanical"
              ratio: 1.0
              interp_using_t: True
              closest_using_t: True
              sparse_interpolate: True
              use_png_depth: True
              max_depth: 60
              ims_pattern: '{frame:05d}.jpg'
              mks_pattern: '{frame:05d}.png'
              dps_pattern: '{frame:05d}.png'
              prob: 1.0
              is_bussi_data: True

            - dataset_name: "parking_mechanical_fisheye"
              ratio: 1.0
              interp_using_t: True
              closest_using_t: True
              sparse_interpolate: True
              use_png_depth: True
              max_depth: 60
              ims_pattern: '{frame:05d}.jpg'
              mks_pattern: '{frame:05d}.png'
              dps_pattern: '{frame:05d}.png'
              prob: 1.0
              is_bussi_data: True
              view_sample: [6, null, 1]

            - dataset_name: "bussinessparking"
              ratio: 1.0
              interp_using_t: True
              closest_using_t: True
              sparse_interpolate: True
              use_png_depth: True
              max_depth: 60
              ims_pattern: '{frame:05d}.jpg'
              dps_pattern: '{frame:05d}.png'
              prob: 0.3
              is_bussi_data: True

            - dataset_name: "bussinessdriving" # 8421 scenes
              ratio: 1.0
              interp_using_t: True
              closest_using_t: True
              sparse_interpolate: True
              use_png_depth: True
              max_depth: 60
              ims_pattern: '{frame:05d}.jpg'
              dps_pattern: '{frame:05d}.png'
              prob: 1.0
              is_bussi_data: True

            - type: MultiviewPointDataset
              ddp_shard_dataset: False
              dataloading_workers: 16  # xy: pls set dataloading_workers here
              n_rays: -1
              proc_max_size: -1 # xy: use this to resize the image
              proc_align_size: 1 # xy: align the image to this size
              max_size: 518 # use this to resize the image
              align_size: 14 # align the image to this size
              disk_dataset: True # to avoid loading all data into memory
              dist_opt_K: False # no distortion for synthetic data
              use_depths: True # use ground truth depths
              use_vhulls: False
              view_sample: [0, null, 1]
              frame_sample: [0, null, 1]
              source_type: MULTIVIEWSEQ
              extra_src_pool: 16  # expand the source pool to twice the number of sources
              ref_view_type: random_front_ref_view # choice: front_ref_view, random_front_ref_view, random_ref_view
              scale: 15.0
              scale_type: MANUAL
              meta_file: __meta_3ddr.pkl
              use_3ddr: True
              portrait_check: False
              center_crop: True  # added by xiaoyang; MAKE fx==fy does not change and the optical center (cx, cy) is at the center of the image
              limit_max_aspect_ratio_as_original_ratio: False  # added by xiaoyang; limit the maximum aspect ratio as the original image ratio
              aug_scale: 0.1 # fov augmentation
              aug_scale_ratio: 1.0
              aug_image: True # image augmentation
              aug_image_cojit: True
              aug_image_cojit_ratio: 0.3 # 30% of the time, use individual image augmentation for each source
              shared_aug_scale_value: True
              min_depth_quantile: 0.0
              max_depth_quantile: 1.0
              n_srcs_list: &train_n_srcs_list [
                  1,
                  2,
                  3,
                  4,
                  5,
                  6,
                  7,
                  8,
                  9,
                  10,
                  11,
                  12,
                  13,
                  14,
                  15,
                  16,
                  17,
                  18,
                  19,
                  20,
                  21,
                  22,
                  23
                ]
              n_srcs_prob: &train_n_srcs_probs [
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0
                ]
    batch_sampler_cfg:  # config of class ImageBasedBatchSampler; NOTE that if this is set, the n_srcs_list and n_srcs_prob in the dataset_cfg will be ignored
        aspect_ratio_range: [0.5, 0.85] # random aspect ratio range
        n_srcs_list: *train_n_srcs_list  # copied from dataset_cfg
        n_srcs_prob: *train_n_srcs_probs  # copied from dataset_cfg
        # n_frames_batch: 64

val_dataloader_cfg:
    dataset_cfg:
        _delete_: True
        type: GeneralizableDataset
        split: VAL
        meta_roots:
            # # mechanical fisheye test datasets
            - /horizon-bucket/perception-dataprocess/4dlabel/static_visual/002_vggt_data/evc_data/business_data/parking_data/20250630_mechanical_at128_eval
            # mechanical test datasets 10v
            - /horizon-bucket/perception-dataprocess/4dlabel/static_visual/002_vggt_data/evc_data/business_data/parking_data/20250630_mechanical_at128_eval
            # driving test datasets 6v
            - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/yingfeng.cai/evc_data/business_data/driving_data/20250521/test
            # - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/yingfeng.cai/evc_data/business_data/driving_data/20250521/test/Site_116_25036670559007_40_04189202692854_20250411-184249-249467_Site_116_25037_40_04189_0_20250512221403/DZ907_20250322_093818

        metaset_cfgs:
            - dataset_name: "parking_fisheye_test"
              ratio: 1.0
              interp_using_t: True
              closest_using_t: True
              sparse_interpolate: True
              min_depth: 0.5
              max_depth: 60
              use_png_depth: True
              ims_pattern: '{frame:05d}.jpg'
              mks_pattern: '{frame:05d}.png'
              dps_pattern: '{frame:05d}.png'
              is_bussi_data: True

            - dataset_name: "parking_test"
              ratio: 1.0
              interp_using_t: True
              closest_using_t: True
              sparse_interpolate: True
              min_depth: 0.5
              max_depth: 60
              use_png_depth: True
              ims_pattern: '{frame:05d}.jpg'
              mks_pattern: '{frame:05d}.png'
              dps_pattern: '{frame:05d}.png'
              is_bussi_data: True
              view_sample: [6, null, 1]

            - dataset_name: "driving_test"
              ratio: 1.0
              interp_using_t: True
              closest_using_t: True
              sparse_interpolate: True
              min_depth: 2
              max_depth: 60
              ims_pattern: '{frame:05d}.jpg'
              dps_pattern: '{frame:05d}.exr'
              is_bussi_data: True
            #   depth_mask_th: 0.774


            - type: MultiviewPointDataset
              ddp_shard_dataset: False
              n_rays: -1
              proc_max_size: -1 # use this to resize the image
              proc_align_size: 1 # align the image to this size
              max_size: 518 # use this to resize the image
              align_size: 14 # align the image to this size
              disk_dataset: True # to avoid loading all data into memory
              view_sample: [0, null, 1]
              frame_sample: [0, null, 1]
              n_srcs_list: &val_n_srcs_list [23]
              n_srcs_prob: &val_n_srcs_probs [1.0]
              min_depth_quantile: 0.0
              max_depth_quantile: 1.0
              source_type: MULTIVIEWSEQ
              extra_src_pool: 5  # expand the source pool to twice the number of sources
              dist_opt_K: False # no distortion for synthetic data
              use_depths: True # use ground truth depths for evaluation
              use_world_coord: True
              scale: 15.0
              scale_type: MANUAL
              use_3ddr: True
              meta_file: __meta_3ddr.pkl

    sampler_cfg:
        type: DistributedSequentialSampler
        view_sample: [0, null, 1]
        frame_sample: [0, null, 1500]
    batch_sampler_cfg:
        n_srcs_list: *val_n_srcs_list  # copied from dataset_cfg
        n_srcs_prob: *val_n_srcs_probs  # copied from dataset_cfg

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}