run:
  name: b11klwarmupend_nosvb_34pt_pointcloud_nrgbd_rerun_20260505
  gpu_ids: "3,7"
  device: auto
  output_root: /horizon-bucket/saturn_v_dev/01_users/feng01.zhou/projects/meshx/baseline/result/unified_eval/20260505_b11klwarmupend_nosvb_34pt/pointcloud_nrgbd_rerun
  skip_existing: false
  continue_on_error: true
model:
  kind: custom
  checkpoint: /horizon-bucket/saturn_v_dev/01_users/feng01.zhou/projects/meshx/baseline/trained_model/vggt/official/finetune_5090_sparse_20260502_b11klwarmupend_13ds_topk1024_l9_19_nosvb_core4val_v3/34.pt
  config: aidi/configs/vggt/finetune_5090_sparse_topk1024_l9_19_p34_record.yaml
datasets:
  nrgbd:
    dataset_root: /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/zinan.lv/dataset_point/NRGBD
    pointcloud:
      sparse:
        enabled: true
        max_sequences: 0
      dense:
        enabled: true
        max_sequences: 0
