extends: eval_20260508_four_baselines_all_tasks_base.yaml

run:
  name: four_baselines_indexer_pi3_ckpt54_all_tasks_20260508
  output_root: /horizon-bucket/saturn_v_dev/01_users/feng01.zhou/projects/meshx/baseline/result/unified_eval/20260508_four_baselines/indexer_pi3_ckpt54
  env:
    PYTORCH_CUDA_ALLOC_CONF: expandable_segments:True
    VGGT_INDEXER_TOPK_OUTER_QUERY_CHUNK: "8192"

model:
  kind: pi3
  checkpoint: /horizon-bucket/saturn_v_dev/01_users/feng01.zhou/projects/meshx/baseline/record/pi3/native_sparse/pi3_native_sparse_vggt15_ckpt24_dynres_topk1024_l9_17_lw10_splitclip_static0_depthgt_20260505_0335/outputs/pi3_native_sparse_vggt15_ckpt24_dynres_topk1024_l9_17_lw10_splitclip_static0_depthgt_20260505_0335/ckpts/checkpoint_54/pytorch_model.bin
  pi3_config: /horizon-bucket/saturn_v_dev/01_users/feng01.zhou/projects/meshx/baseline/record/pi3/native_sparse/pi3_native_sparse_vggt15_ckpt24_dynres_topk1024_l9_17_lw10_splitclip_static0_depthgt_20260505_0335/outputs/pi3_native_sparse_vggt15_ckpt24_dynres_topk1024_l9_17_lw10_splitclip_static0_depthgt_20260505_0335/.hydra/config.yaml
  pi3_model_impl: native_sparse
  pi3_native_root: aidi/third_party/pi3_training
  pi3_root: /horizon-bucket/saturn_v_dev/01_users/feng01.zhou/projects/meshx/baseline/external_refs/pi3-official2_clean
