#!/usr/bin/env bash
set -euo pipefail

# Pi3 indexer sparse stage (resume from warm-up ckpt).

USER_EXTRA_OVERRIDES=${EXTRA_OVERRIDES:-""}
LOAD_VGGT=${LOAD_VGGT:-0}
INDEXER_LAYERS=${INDEXER_LAYERS:-"9-21"}
INDEXER_LAYERS_TAG=${INDEXER_LAYERS_TAG:-${INDEXER_LAYERS//[^0-9A-Za-z]/_}}
TOPK=${TOPK:-512}
SPARSE_LR=${SPARSE_LR:-}
SPARSE_LR_DECAY=${SPARSE_LR_DECAY:-scheduler}
SPARSE_MIN_LR=${SPARSE_MIN_LR:-}
SPARSE_LOSS_WEIGHT=${SPARSE_LOSS_WEIGHT:-}
SPARSE_COMPUTE_LOSS=${SPARSE_COMPUTE_LOSS:-1}
SPARSE_FREEZE_INDEXER=${SPARSE_FREEZE_INDEXER:-0}
SPARSE_WARMUP_STEPS=${SPARSE_WARMUP_STEPS:-0}
SPARSE_START_STEP=${SPARSE_START_STEP:-${SPARSE_WARMUP_STEPS}}
SPARSE_WARMUP_ONLY_INDEXER_LOSS=${SPARSE_WARMUP_ONLY_INDEXER_LOSS:-0}
SPARSE_WARMUP_ONLY_INDEXER_TRAIN=${SPARSE_WARMUP_ONLY_INDEXER_TRAIN:-0}
SPARSE_WARMUP_OPTIMIZER_FILTER=${SPARSE_WARMUP_OPTIMIZER_FILTER:-1}
SPARSE_WARMUP_LOSS_WEIGHT=${SPARSE_WARMUP_LOSS_WEIGHT:-}
SPARSE_WARMUP_LR=${SPARSE_WARMUP_LR:-}
SPARSE_WARMUP_INDEXER_LOSS_MODE=${SPARSE_WARMUP_INDEXER_LOSS_MODE:-}
SPARSE_OBJECTIVE_VALUE_GATE=${SPARSE_OBJECTIVE_VALUE_GATE:-0}
SPARSE_OBJECTIVE_VALUE_GATE_SCALE=${SPARSE_OBJECTIVE_VALUE_GATE_SCALE:-}
SPARSE_OBJECTIVE_VALUE_GATE_TAU=${SPARSE_OBJECTIVE_VALUE_GATE_TAU:-}
SPARSE_OBJECTIVE_VALUE_GATE_QUERY_CHUNK_SIZE=${SPARSE_OBJECTIVE_VALUE_GATE_QUERY_CHUNK_SIZE:-}
SPARSE_OBJECTIVE_VALUE_GATE_VALUE_CHUNK_SIZE=${SPARSE_OBJECTIVE_VALUE_GATE_VALUE_CHUNK_SIZE:-}
SPARSE_OBJECTIVE_VALUE_GATE_GATHER_CHUNK_SIZE=${SPARSE_OBJECTIVE_VALUE_GATE_GATHER_CHUNK_SIZE:-}
SPARSE_SCORE_DTYPE=${SPARSE_SCORE_DTYPE:-float16}
TRAIN_MODEL_DTYPE=${TRAIN_MODEL_DTYPE:-fp16}
TRAIN_RES=${TRAIN_RES:-518}
TEST_RES=${TEST_RES:-${TRAIN_RES}}
TRAIN_DYNAMIC_RES=${TRAIN_DYNAMIC_RES:-0}
TRAIN_DYNAMIC_ASPECT_RATIO_RANGE=${TRAIN_DYNAMIC_ASPECT_RATIO_RANGE:-"[0.5,2.0]"}
TRAIN_DYNAMIC_PIXEL_COUNT_RANGE=${TRAIN_DYNAMIC_PIXEL_COUNT_RANGE:-"[100000,255000]"}
TRAIN_DYNAMIC_PATCH_SIZE=${TRAIN_DYNAMIC_PATCH_SIZE:-14}
TRAIN_DYNAMIC_NUM_RESOLUTION=${TRAIN_DYNAMIC_NUM_RESOLUTION:--1}
PI3_FIND_UNUSED_PARAMETERS=${PI3_FIND_UNUSED_PARAMETERS:-0}
PI3_STATIC_GRAPH=${PI3_STATIC_GRAPH:-0}
PI3_SPARSE_HEAD_CHUNK_SIZE=${PI3_SPARSE_HEAD_CHUNK_SIZE:-}
PI3_SPARSE_VIEW_CHUNK_SIZE=${PI3_SPARSE_VIEW_CHUNK_SIZE:-}
PI3_SPARSE_QUERY_CHUNK_SIZE=${PI3_SPARSE_QUERY_CHUNK_SIZE:-}
INDEXER_HEAD_CHUNK_SIZE=${INDEXER_HEAD_CHUNK_SIZE:-${PI3_SPARSE_HEAD_CHUNK_SIZE:-4}}
INDEXER_SCORE_HEAD_CHUNK_SIZE=${INDEXER_SCORE_HEAD_CHUNK_SIZE:-${PI3_SPARSE_HEAD_CHUNK_SIZE:-4}}
INDEXER_SCORE_KEY_CHUNK_SIZE=${INDEXER_SCORE_KEY_CHUNK_SIZE:-${PI3_SPARSE_QUERY_CHUNK_SIZE:-4096}}
PI3_NUM_DEC_BLK_NOT_TO_CHECKPOINT=${PI3_NUM_DEC_BLK_NOT_TO_CHECKPOINT:-0}
PI3_DECODER_ATTN_BACKEND=${PI3_DECODER_ATTN_BACKEND:-flash}
PI3_QK_NORM_CHUNK_SIZE=${PI3_QK_NORM_CHUNK_SIZE:-2048}
PI3_HEAD_USE_CHECKPOINT=${PI3_HEAD_USE_CHECKPOINT:-1}
PI3_HEAD_VIEW_CHUNK_SIZE=${PI3_HEAD_VIEW_CHUNK_SIZE:-${PI3_SPARSE_VIEW_CHUNK_SIZE:-4}}
PI3_NORMAL_LOSS_VIEW_CHUNK_SIZE=${PI3_NORMAL_LOSS_VIEW_CHUNK_SIZE:-1}
PYTORCH_CUDA_ALLOC_CONF=${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}
RUN_NAME=${RUN_NAME:-"pi3_sparse_$(date +%Y%m%d_%H%M)_layers${INDEXER_LAYERS_TAG}_topk${TOPK}_fp16"}
GPU_IDS=${GPU_IDS:-"0,1,2,3,4,5,6,7"}
NUM_MACHINES=${NUM_MACHINES:-${NUM_NODES:-1}}
NUM_PROCESSES=${NUM_PROCESSES:-${WORLD_SIZE:-$(echo "${GPU_IDS}" | awk -F',' '{print NF}')}}

MODEL_CKPT=${MODEL_CKPT:-""}
if [ -z "${MODEL_CKPT}" ]; then
  echo "[ERROR] MODEL_CKPT is required for sparse stage."
  exit 1
fi

is_truthy() {
  case "${1:-}" in
    1|true|True|TRUE|yes|Yes|YES|on|On|ON) return 0 ;;
    *) return 1 ;;
  esac
}

# VGGT-like data loading knobs (same as warmup script).
SAVE_ROOT=${SAVE_ROOT:-"/horizon-bucket/saturn_v_dev/01_users/${USER:-feng01.zhou}/projects/meshx/baseline"}
PI3_DATASET_CACHE_DIR=${PI3_DATASET_CACHE_DIR:-"${SAVE_ROOT}/cache/pi3_dataset_index"}
PI3_USE_INDEX_CACHE=${PI3_USE_INDEX_CACHE:-1}
PI3_REBUILD_INDEX_CACHE=${PI3_REBUILD_INDEX_CACHE:-0}
PI3_USE_CAMERA_PKL_CACHE=${PI3_USE_CAMERA_PKL_CACHE:-0}
PI3_INDEX_CACHE_WAIT_SEC=${PI3_INDEX_CACHE_WAIT_SEC:-0}
PI3_INDEXING_WORKERS=${PI3_INDEXING_WORKERS:-64}
PI3_LAZY_SEQUENCE_INDEX=${PI3_LAZY_SEQUENCE_INDEX:-1}

DATA_CFG=${DATA_CFG:-meshx_tartanair}
if [ "${DATA_CFG}" = "meshx_pi3_paper_overlap" ]; then
  DATASET_KEYS=("BlendedMVS" "HyperSimTrain" "TarTanAir" "MegaDepth" "ScanNetPP" "Taskonomy" "WildRGBD" "CO3Dv2")
else
  DATASET_KEYS=("TarTanAir")
fi

SPARSE_OVERRIDES=(
  "hydra/hydra_logging=default"
  "hydra/job_logging=custom"
  "train.model_dtype=${TRAIN_MODEL_DTYPE}"
  "model.indexer_cfg.enabled=True"
  "model.indexer_cfg.indexer_layers=${INDEXER_LAYERS}"
  "model.indexer_cfg.topk=${TOPK}"
  "model.indexer_cfg.enable_sparse=True"
  "model.indexer_cfg.warmup_steps=${SPARSE_WARMUP_STEPS}"
  "model.indexer_cfg.sparse_start_step=${SPARSE_START_STEP}"
  "model.indexer_cfg.compute_loss=${SPARSE_COMPUTE_LOSS}"
  "model.indexer_cfg.freeze_indexer=${SPARSE_FREEZE_INDEXER}"
  "model.indexer_cfg.warmup_only_indexer_loss=${SPARSE_WARMUP_ONLY_INDEXER_LOSS}"
  "model.indexer_cfg.warmup_only_indexer_train=${SPARSE_WARMUP_ONLY_INDEXER_TRAIN}"
  "model.indexer_cfg.warmup_optimizer_filter=${SPARSE_WARMUP_OPTIMIZER_FILTER}"
  "model.indexer_cfg.sparse_lr_decay=${SPARSE_LR_DECAY}"
  "model.indexer_cfg.score_dtype=${SPARSE_SCORE_DTYPE}"
  "train.find_unused_parameters=${PI3_FIND_UNUSED_PARAMETERS}"
  "train.static_graph=${PI3_STATIC_GRAPH}"
)

if [ -n "${SPARSE_LR}" ]; then
  SPARSE_OVERRIDES+=("model.indexer_cfg.sparse_lr=${SPARSE_LR}")
fi
if [ -n "${SPARSE_MIN_LR}" ]; then
  SPARSE_OVERRIDES+=("model.indexer_cfg.sparse_min_lr=${SPARSE_MIN_LR}")
fi
if [ -n "${SPARSE_LOSS_WEIGHT}" ]; then
  SPARSE_OVERRIDES+=("model.indexer_cfg.sparse_loss_weight=${SPARSE_LOSS_WEIGHT}")
fi
if [ -n "${SPARSE_WARMUP_LOSS_WEIGHT}" ]; then
  SPARSE_OVERRIDES+=("model.indexer_cfg.warmup_loss_weight=${SPARSE_WARMUP_LOSS_WEIGHT}")
fi
if [ -n "${SPARSE_WARMUP_LR}" ]; then
  SPARSE_OVERRIDES+=("model.indexer_cfg.warmup_lr=${SPARSE_WARMUP_LR}")
fi
if [ -n "${SPARSE_WARMUP_INDEXER_LOSS_MODE}" ]; then
  SPARSE_OVERRIDES+=("model.indexer_cfg.warmup_indexer_loss_mode=${SPARSE_WARMUP_INDEXER_LOSS_MODE}")
fi
SPARSE_OVERRIDES+=("model.indexer_cfg.objective_value_gate_enabled=${SPARSE_OBJECTIVE_VALUE_GATE}")
if [ -n "${SPARSE_OBJECTIVE_VALUE_GATE_SCALE}" ]; then
  SPARSE_OVERRIDES+=("model.indexer_cfg.objective_value_gate_scale=${SPARSE_OBJECTIVE_VALUE_GATE_SCALE}")
fi
if [ -n "${SPARSE_OBJECTIVE_VALUE_GATE_TAU}" ]; then
  SPARSE_OVERRIDES+=("model.indexer_cfg.objective_value_gate_tau=${SPARSE_OBJECTIVE_VALUE_GATE_TAU}")
fi
if [ -n "${SPARSE_OBJECTIVE_VALUE_GATE_QUERY_CHUNK_SIZE}" ]; then
  SPARSE_OVERRIDES+=("model.indexer_cfg.objective_value_gate_query_chunk_size=${SPARSE_OBJECTIVE_VALUE_GATE_QUERY_CHUNK_SIZE}")
fi
if [ -n "${SPARSE_OBJECTIVE_VALUE_GATE_VALUE_CHUNK_SIZE}" ]; then
  SPARSE_OVERRIDES+=("++model.indexer_cfg.objective_value_gate_value_chunk_size=${SPARSE_OBJECTIVE_VALUE_GATE_VALUE_CHUNK_SIZE}")
fi
if [ -n "${SPARSE_OBJECTIVE_VALUE_GATE_GATHER_CHUNK_SIZE}" ]; then
  SPARSE_OVERRIDES+=("++model.indexer_cfg.objective_value_gate_gather_chunk_size=${SPARSE_OBJECTIVE_VALUE_GATE_GATHER_CHUNK_SIZE}")
fi

if [ -n "${INDEXER_HEAD_CHUNK_SIZE}" ]; then
  SPARSE_OVERRIDES+=("model.indexer_cfg.head_chunk_size=${INDEXER_HEAD_CHUNK_SIZE}")
fi
if [ -n "${INDEXER_SCORE_HEAD_CHUNK_SIZE}" ]; then
  SPARSE_OVERRIDES+=("model.indexer_cfg.score_head_chunk_size=${INDEXER_SCORE_HEAD_CHUNK_SIZE}")
fi
if [ -n "${INDEXER_SCORE_KEY_CHUNK_SIZE}" ]; then
  SPARSE_OVERRIDES+=("model.indexer_cfg.score_key_chunk_size=${INDEXER_SCORE_KEY_CHUNK_SIZE}")
fi

if is_truthy "${TRAIN_DYNAMIC_RES}"; then
  SPARSE_OVERRIDES+=(
    "++train.random_reslution=True"
    "++train.aspect_ratio_range=${TRAIN_DYNAMIC_ASPECT_RATIO_RANGE}"
    "++train.pixel_count_range=${TRAIN_DYNAMIC_PIXEL_COUNT_RANGE}"
    "++train.patch_size=${TRAIN_DYNAMIC_PATCH_SIZE}"
    "++train.num_resolution=${TRAIN_DYNAMIC_NUM_RESOLUTION}"
  )
else
  SPARSE_OVERRIDES+=(
    "++train.random_reslution=False"
    "++train.num_resolution=1"
    "++train.resolution=[[${TRAIN_RES},${TRAIN_RES}]]"
  )
fi

DATA_LOADING_OVERRIDES=()
dataset_key=
for dataset_key in "${DATASET_KEYS[@]}"; do
  DATA_LOADING_OVERRIDES+=("++train_dataset.${dataset_key}.use_camera_pkl_cache=${PI3_USE_CAMERA_PKL_CACHE}")
  DATA_LOADING_OVERRIDES+=("++test_dataset.${dataset_key}.use_camera_pkl_cache=${PI3_USE_CAMERA_PKL_CACHE}")
  DATA_LOADING_OVERRIDES+=("++train_dataset.${dataset_key}.use_index_cache=${PI3_USE_INDEX_CACHE}")
  DATA_LOADING_OVERRIDES+=("++test_dataset.${dataset_key}.use_index_cache=${PI3_USE_INDEX_CACHE}")
  DATA_LOADING_OVERRIDES+=("++train_dataset.${dataset_key}.rebuild_index_cache=${PI3_REBUILD_INDEX_CACHE}")
  DATA_LOADING_OVERRIDES+=("++test_dataset.${dataset_key}.rebuild_index_cache=${PI3_REBUILD_INDEX_CACHE}")
  DATA_LOADING_OVERRIDES+=("++train_dataset.${dataset_key}.index_cache_dir=${PI3_DATASET_CACHE_DIR}")
  DATA_LOADING_OVERRIDES+=("++test_dataset.${dataset_key}.index_cache_dir=${PI3_DATASET_CACHE_DIR}")
  DATA_LOADING_OVERRIDES+=("++train_dataset.${dataset_key}.index_cache_wait_sec=${PI3_INDEX_CACHE_WAIT_SEC}")
  DATA_LOADING_OVERRIDES+=("++test_dataset.${dataset_key}.index_cache_wait_sec=${PI3_INDEX_CACHE_WAIT_SEC}")
done

join_by() {
  local IFS="$1"
  shift
  echo "$*"
}

build_overrides() {
  local items=("$@")
  local filtered=()
  local item
  for item in "${items[@]}"; do
    if [ -n "${item}" ]; then
      filtered+=("${item}")
    fi
  done
  join_by ';' "${filtered[@]}"
}

EXTRA_OVERRIDES_ALL=$(build_overrides \
  "${SPARSE_OVERRIDES[@]}" \
  "${DATA_LOADING_OVERRIDES[@]}" \
  "${USER_EXTRA_OVERRIDES}")

export STAGE=${STAGE:-sparse}
export TRAIN_CFG=${TRAIN_CFG:-train_pi3_lowres_indexer_sparse}
export DATA_CFG
export LOAD_VGGT
export RUN_NAME
export TOPK
export SPARSE_LR_DECAY
export SPARSE_MIN_LR
export SPARSE_COMPUTE_LOSS
export SPARSE_FREEZE_INDEXER
export SPARSE_WARMUP_STEPS
export SPARSE_START_STEP
export SPARSE_WARMUP_ONLY_INDEXER_LOSS
export SPARSE_WARMUP_ONLY_INDEXER_TRAIN
export SPARSE_WARMUP_OPTIMIZER_FILTER
export SPARSE_WARMUP_LOSS_WEIGHT
export SPARSE_WARMUP_LR
export SPARSE_WARMUP_INDEXER_LOSS_MODE
export INDEXER_LAYERS
export MODEL_CKPT
export EXTRA_OVERRIDES="${EXTRA_OVERRIDES_ALL}"
export PI3_DATASET_CACHE_DIR
export PI3_INDEX_CACHE_WAIT_SEC
export PI3_INDEXING_WORKERS
export PI3_LAZY_SEQUENCE_INDEX
export PYTORCH_CUDA_ALLOC_CONF
export PI3_NUM_DEC_BLK_NOT_TO_CHECKPOINT
export PI3_DECODER_ATTN_BACKEND
export PI3_QK_NORM_CHUNK_SIZE
export PI3_HEAD_USE_CHECKPOINT
export PI3_HEAD_VIEW_CHUNK_SIZE
export PI3_NORMAL_LOSS_VIEW_CHUNK_SIZE
export GPU_IDS
export NUM_MACHINES
export NUM_PROCESSES
export CUDA_VISIBLE_DEVICES="${GPU_IDS}"

echo "[INFO] DATA_CFG=${DATA_CFG} DATASET_KEYS=${DATASET_KEYS[*]}"
echo "[INFO] GPU_IDS=${GPU_IDS} CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES} NUM_PROCESSES=${NUM_PROCESSES} NUM_MACHINES=${NUM_MACHINES}"
echo "[INFO] MODEL_CKPT=${MODEL_CKPT}"
echo "[INFO] INDEXER_LAYERS=${INDEXER_LAYERS} TOPK=${TOPK}"
echo "[INFO] SPARSE_COMPUTE_LOSS=${SPARSE_COMPUTE_LOSS} SPARSE_FREEZE_INDEXER=${SPARSE_FREEZE_INDEXER}"
echo "[INFO] SPARSE_WARMUP_STEPS=${SPARSE_WARMUP_STEPS} SPARSE_START_STEP=${SPARSE_START_STEP} SPARSE_WARMUP_ONLY_INDEXER_LOSS=${SPARSE_WARMUP_ONLY_INDEXER_LOSS} SPARSE_WARMUP_ONLY_INDEXER_TRAIN=${SPARSE_WARMUP_ONLY_INDEXER_TRAIN} SPARSE_WARMUP_OPTIMIZER_FILTER=${SPARSE_WARMUP_OPTIMIZER_FILTER}"
echo "[INFO] SPARSE_WARMUP_LOSS_WEIGHT=${SPARSE_WARMUP_LOSS_WEIGHT:-<config-default>} SPARSE_WARMUP_LR=${SPARSE_WARMUP_LR:-<config-default>} SPARSE_WARMUP_INDEXER_LOSS_MODE=${SPARSE_WARMUP_INDEXER_LOSS_MODE:-<config-default>}"
echo "[INFO] TRAIN_MODEL_DTYPE=${TRAIN_MODEL_DTYPE} SPARSE_LR=${SPARSE_LR:-<config-default>} SPARSE_LR_DECAY=${SPARSE_LR_DECAY} SPARSE_MIN_LR=${SPARSE_MIN_LR:-<config-default>} SPARSE_LOSS_WEIGHT=${SPARSE_LOSS_WEIGHT:-<config-default>} SPARSE_SCORE_DTYPE=${SPARSE_SCORE_DTYPE}"
echo "[INFO] TRAIN_DYNAMIC_RES=${TRAIN_DYNAMIC_RES} TRAIN_RES=${TRAIN_RES} TEST_RES=${TEST_RES}"
echo "[INFO] PI3_FIND_UNUSED_PARAMETERS=${PI3_FIND_UNUSED_PARAMETERS} PI3_STATIC_GRAPH=${PI3_STATIC_GRAPH}"
echo "[INFO] INDEXER_CHUNKS=head:${INDEXER_HEAD_CHUNK_SIZE:-<config-default>} score_head:${INDEXER_SCORE_HEAD_CHUNK_SIZE:-<config-default>} score_key:${INDEXER_SCORE_KEY_CHUNK_SIZE:-<config-default>}"
echo "[INFO] PI3_MEMORY=dec_not_ckpt:${PI3_NUM_DEC_BLK_NOT_TO_CHECKPOINT} dec_attn:${PI3_DECODER_ATTN_BACKEND} qk_chunk:${PI3_QK_NORM_CHUNK_SIZE} head_ckpt:${PI3_HEAD_USE_CHECKPOINT} head_view_chunk:${PI3_HEAD_VIEW_CHUNK_SIZE} normal_loss_view_chunk:${PI3_NORMAL_LOSS_VIEW_CHUNK_SIZE}"
echo "[INFO] PYTORCH_CUDA_ALLOC_CONF=${PYTORCH_CUDA_ALLOC_CONF}"
echo "[INFO] PI3_DATASET_CACHE_DIR=${PI3_DATASET_CACHE_DIR}"
echo "[INFO] PI3_USE_INDEX_CACHE=${PI3_USE_INDEX_CACHE} PI3_REBUILD_INDEX_CACHE=${PI3_REBUILD_INDEX_CACHE}"
echo "[INFO] PI3_USE_CAMERA_PKL_CACHE=${PI3_USE_CAMERA_PKL_CACHE} PI3_INDEX_CACHE_WAIT_SEC=${PI3_INDEX_CACHE_WAIT_SEC} PI3_INDEXING_WORKERS=${PI3_INDEXING_WORKERS}"
echo "[INFO] PI3_LAZY_SEQUENCE_INDEX=${PI3_LAZY_SEQUENCE_INDEX}"
echo "[INFO] EXTRA_OVERRIDES=${EXTRA_OVERRIDES}"

bash aidi/scripts/pi3/train_pi3_official.sh
