import numpy as np
import math
from typing import List
import torch
import torch.distributed as dist

from easyvolcap.engine import EVALUATORS, cfg
from easyvolcap.utils.console_utils import *
from easyvolcap.utils.base_utils import dotdict
from easyvolcap.utils.json_utils import serialize
from easyvolcap.utils.data_utils import Visualization
from easyvolcap.utils.metric_utils import psnr, ssim, lpips, Metrics
from easyvolcap.utils.dist_utils import get_distributed, get_world_size, get_rank
from easyvolcap.runners.visualizers.volumetric_video_visualizer import VolumetricVideoVisualizer


def _metric_nonfinite_fields(metric: dotdict) -> List[str]:
    fields = []
    for key, value in metric.items():
        if isinstance(value, torch.Tensor):
            if value.numel() == 0:
                continue
            try:
                value = value.detach().float().mean().item()
            except Exception:
                continue
        elif isinstance(value, np.ndarray):
            if value.size == 0:
                continue
            try:
                value = float(np.asarray(value).mean())
            except Exception:
                continue
        elif isinstance(value, (np.floating, np.integer)):
            value = float(value)
        elif isinstance(value, bool):
            value = float(value)
        elif not isinstance(value, (int, float)):
            continue

        if not math.isfinite(float(value)):
            fields.append(key)
    return fields


def _filter_nonfinite_metrics(metrics: List[dotdict]):
    filtered = []
    dropped = []
    for metric in metrics:
        bad_fields = _metric_nonfinite_fields(metric)
        if bad_fields:
            dropped.append(dotdict(
                path=metric.get('path', ''),
                camera=metric.get('camera', None),
                frame=metric.get('frame', metric.get('frame_index', None)),
                fields=bad_fields,
            ))
            continue
        filtered.append(metric)
    return filtered, dropped


@EVALUATORS.register_module()
class VolumetricVideoEvaluator(VolumetricVideoVisualizer):
    def __init__(self,
                 skip_time_in_summary: int = 0,  # skip first 5 image in summary
                 result_dir: str = cfg.runner_cfg.visualizer_cfg.result_dir,  # MARK: GLOBAL
                 save_tag: str = cfg.runner_cfg.visualizer_cfg.save_tag,  # MARK: GLOBAL
                 metrics_file: str = 'metrics.json',
                 compute_metrics: List[str] = ['PSNR', 'SSIM', 'LPIPS'],
                 **kwargs,
                 ) -> None:
        super().__init__(verbose=False, result_dir=result_dir, save_tag=save_tag, **kwargs)
        self.skip_time_in_summary = skip_time_in_summary
        self.metrics = []
        self.metrics_file = metrics_file
        self.compute_metrics = [getattr(Metrics, m) for m in compute_metrics]

    def evaluate(self, output: dotdict, batch: dotdict, print: bool = True):
        # TODO: This is a bit wasteful since the images are already generated by the visualizer
        img, img_gt, _ = super().generate_type(output, batch, Visualization.RENDER)
        metrics = dotdict()

        # Read rendering time from output
        if 'time' in output.keys() and output.time != 0:
            metrics.time = output.time

        if img_gt is not None:
            # Computing metrics
            img, img_gt = img[..., :3], img_gt[..., :3]  # image loss are compute in 3 channels (last are only for saving)
            for compute in self.compute_metrics:
                metrics[compute.__name__] = compute(img, img_gt)  # actual computation of the metrics

        if len(metrics):
            # Record the iteration for logging
            self.iter = batch.meta.iter
            self.metrics.append(metrics)

            # For recording
            c = batch.meta.camera_index.item()
            f = batch.meta.frame_index.item()
            if print: log(f'camera: {c}', f'frame: {f}', metrics)
            metrics.camera = c
            metrics.frame = f

        scalar_stats = dotdict({f'{k}_frame{f:04d}_cam{c:04d}': v for k, v in metrics.items()})
        return scalar_stats

    def synchronize_metrics(self, max_size: Optional[int] = None):
        # Early return if not in distributed mode
        if not get_distributed() or get_world_size() == 1:
            return
        # Try to synchronize the metrics
        try:
            # Gather the metrics from all processes
            rank_metrics = [None] * get_world_size()
            dist.all_gather_object(rank_metrics, self.metrics)
            if not get_rank():
                # Combine all metrics on rank 0.
                #
                # Different ranks can legitimately own different numbers of
                # evaluation samples when `test_with_ddp_sharding=True`
                # (e.g. scene-level sharding on ETH3D/DTU). The previous
                # implementation assumed every rank had the same list length and
                # indexed by `len(rank_metrics[0])`, which can raise
                # `IndexError` and silently drop non-zero-rank samples.
                sync_metrics = []
                for metrics in rank_metrics:
                    if not metrics:
                        continue
                    sync_metrics.extend(metrics)
                if max_size is not None and len(sync_metrics) > max_size:
                    log(f"Truncating metrics to {max_size} from {len(sync_metrics)}")
                    sync_metrics = sync_metrics[:max_size]
                self.metrics = sync_metrics
            else:
                # Clear the metrics in other ranks
                self.metrics.clear()
        except Exception as e:
            log(red(f"Error during metrics synchronization: {e}"))
            log(yellow("Keeping original metrics due to synchronization error"))

    def summarize(self):
        summary = dotdict()
        dropped = []
        metrics = self.metrics
        if len(metrics):
            metrics, dropped = _filter_nonfinite_metrics(metrics)
        if len(metrics):
            for key in metrics[0].keys():
                values = [m[key] for m in metrics]
                if key == 'time':
                    if np.sum(values) == 0: continue  # timer has not been enabled
                    values = values[self.skip_time_in_summary:]
                    summary[f'{key}{self.skip_time_in_summary:}+_mean'] = np.mean(values).astype(float).item()
                    summary[f'{key}{self.skip_time_in_summary:}+_std'] = np.std(values).astype(float).item()
                elif key == 'camera':
                    pass
                elif key == 'frame':
                    pass
                else:
                    summary[f'{key}_mean'] = np.mean(values).astype(float).item()
                    summary[f'{key}_std'] = np.std(values).astype(float).item()

        if len(summary):
            log(summary)

        if len(metrics) or len(dropped):
            metric = dotdict()
            metric.summary = summary
            metric.metrics = metrics
            if len(dropped):
                metric.dropped_nonfinite = dropped
            metric_path = join(self.result_dir, f'{self.iter:08d}', self.metrics_file)
            try:
                if not exists(dirname(metric_path)):
                    os.makedirs(dirname(metric_path), exist_ok=True)
                with open(metric_path, 'w') as f:
                    # TODO: After finding out the offending object, we can remove the try-except block and serialize call
                    json.dump(serialize(metric), f, indent=4)
                log(yellow(f'Evaluation metrics saved to {blue(metric_path)}'))
            except Exception as e:
                log(red(f'Error in dumping evaluation metrics to {blue(metric_path)}: {e}'))

            self.metrics.clear()  # clear mean after extracting summary
        return summary


@EVALUATORS.register_module()
class NoopEvaluator(VolumetricVideoVisualizer):
    def __init__(self) -> None:
        self.metrics = []

    def evaluate(self, output: dotdict, batch: dotdict, **kwargs):
        return dotdict()

    def synchronize_metrics(self, max_size=None):
        return

    def summarize(self):
        return dotdict()


@EVALUATORS.register_module()
class ScalarEvaluator:
    """Aggregate scalar_stats from model outputs for validation."""
    def __init__(self, keys: List[str] = None, print_summary: bool = True) -> None:
        self.keys = set(keys) if keys else None
        self.print_summary = print_summary
        self.metrics = []

    @staticmethod
    def _to_float(value):
        if isinstance(value, torch.Tensor):
            return value.detach().mean().item()
        if isinstance(value, np.ndarray):
            return float(np.mean(value))
        if isinstance(value, (int, float)):
            return float(value)
        return None

    def evaluate(self, output: dotdict, batch: dotdict, **kwargs):
        scalar_stats = getattr(output, "scalar_stats", None)
        metrics = dotdict()
        if scalar_stats:
            for key, value in scalar_stats.items():
                if self.keys is not None and key not in self.keys:
                    continue
                val = self._to_float(value)
                if val is None:
                    continue
                metrics[key] = val

        if not metrics and hasattr(output, "loss"):
            val = self._to_float(output.loss)
            if val is not None:
                metrics.loss = val

        if len(metrics):
            self.metrics.append(metrics)

        return metrics

    def synchronize_metrics(self, max_size=None):
        if not get_distributed() or get_world_size() == 1:
            return
        try:
            rank_metrics = [None] * get_world_size()
            dist.all_gather_object(rank_metrics, self.metrics)
            if not get_rank():
                sync_metrics = []
                for i in range(len(rank_metrics[0])):
                    for metrics in rank_metrics:
                        sync_metrics.append(metrics[i])
                if max_size is not None and len(sync_metrics) > max_size:
                    log(f"Truncating metrics to {max_size} from {len(sync_metrics)}")
                    sync_metrics = sync_metrics[:max_size]
                self.metrics = sync_metrics
            else:
                self.metrics.clear()
        except Exception as e:
            log(red(f"Error during metrics synchronization: {e}"))
            log(yellow("Keeping original metrics due to synchronization error"))

    def summarize(self):
        summary = dotdict()
        if len(self.metrics):
            keys = sorted({k for m in self.metrics for k in m.keys()})
            for key in keys:
                values = [m[key] for m in self.metrics if key in m]
                if not values:
                    continue
                summary[f'{key}_mean'] = float(np.mean(values))
                summary[f'{key}_std'] = float(np.std(values))

        if len(summary) and self.print_summary:
            log(summary)

        if len(self.metrics):
            self.metrics.clear()
        return summary
