# VGGT v2 config.
# 
# 修改内容：
# 1. ase默认的图片为旋转90度的图片，这里强制预先旋转90度
# 2. 数据处理开启center_crop
# 3. 数据处理开启limit_max_aspect_ratio_as_original_ratiox`

configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/vggt.yaml # network model configuration

# FSDP: https://docs.pytorch.org/tutorials/intermediate/FSDP_tutorial.html
fsdp_enabled: False
runner_cfg:
    # fsdp_shard_class_list: ['NestedTensorBlock', 'Block', 'DPTHead', 'CameraHead']
    gradient_accumulation_steps: 2
    ep_iter: 1000 # 2x the default for using gradient accumulation
    log_interval: 50 # log every 20 iterations for using gradient accumulation
    empty_cache_ep: 1 # eval_ep
    print_test_progress: False  # xiaoyang: it seems tqdm makes data preloading?
    test_with_ddp_sharding: &test_with_ddp_sharding True
    test_before_first_epoch: True
    eval_ep: 10

model_cfg:
    sampler_cfg:  # config of class VGGTSampler
        dinov2_ckpt: "/horizon-bucket/saturn_v_dev/01_users/tao02.xie/projects/GFM/gfm/data/trained_model/dinov2/backbones/dinov2_vitl14_reg4_pretrain.pth"
        vggt_batching: True # use the custom VGGT batching

dataloader_cfg:
    dataset_cfg:  # config of class GeneralizableDataset
        _delete_: True
        type: GeneralizableDataset
        split: TRAIN
        runtime_build: True  # modified by xiaoyang, avoid loading all data into memory before training
        delete_after_runtime_build: True  # set to True if too many training scenes
        global_sharding: True
        dataset_indexing: True
        n_frames_batch: 24
        parallel_loading: True
        dataloading_workers: 64
        meta_file: /horizon-bucket/saturn_v_4dlabel/008_Simulation/001_users/xiaoyang.guo/data/gfm_v1_dl3dv.pkl
        meta_roots:
            # Synthetic datasets
            - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/yingfeng.cai/evc_data/blendedmvs/train
            - /horizon-bucket/saturn_v_dev/users/tao02.xie/datasets/hypersim/train
            - /horizon-bucket/saturn_v_dev/users/tao02.xie/datasets/hypersim/val
            - /horizon-bucket/saturn_v_dev/users/tao02.xie/datasets/mvs_synth/GTAV_1080
            - /horizon-bucket/saturn_v_dev/users/tao02.xie/datasets/replica_niceslam
            - /horizon-bucket/saturn_v_dev/users/tao02.xie/datasets/tartanair
            - /horizon-bucket/saturn_v_dev/users/tao02.xie/datasets/vkitti2
            # - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/yingfeng.cai/evc_data/point_odyssey/train
            # - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/yingfeng.cai/evc_data/point_odyssey/val
            - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/tao02.xie/datasets/ase
            - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/tao02.xie/datasets/adt
            # Real-world datasets
            # - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/yingfeng.cai/evc_data/ARKitscenes/Training
            - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/yingfeng.cai/evc_data/megadepth
            - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/yingfeng.cai/evc_data/scannetpp
            # - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/yingfeng.cai/evc_data/scannetpp_v2/nvs_sem_train
            # - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/yingfeng.cai/evc_data/scannetpp_v2/nvs_sem_val
            - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/yingfeng.cai/evc_data/taskonomy
            - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/yingfeng.cai/evc_data/wildrgbd/train
            - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/tao02.xie/datasets/mapfree/train
            - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/yingfeng.cai/evc_data/co3dv2/train
            - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/tao02.xie/datasets/mapillary/train
            - /horizon-bucket/saturn_v_4dlabel/004_vision/01_users/tao02.xie/datasets/mapillary/val
            - /horizon-bucket/perception-dataprocess/4dlabel/static_visual/002_vggt_data/evc_data/dl3dv
        metaset_cfgs:  # configs for each dataset, the last one is the default config
            # The unified ratio is only used for a placeholder
            # The actual resolution is determined by the max_size, lazy resizing
            # Synthetic datasets
            - dataset_name: "blendedmvs"  # 477 high-quality scenes
              ratio: 1.0
              prob: 1.0
            - dataset_name: "hypersim/train"  # 613 high-quality synthetic scenes
              ratio: 1.0
              max_depth_quantile: 0.99
              prob: 1.0
            - dataset_name: "hypersim/val"  # 77 high-quality synthetic scenes
              ratio: 1.0
              max_depth_quantile: 0.99
              prob: 0.1
            - dataset_name: "GTAV_1080"  # 120 game scenes
              ratio: 1.0
              min_depth_quantile: 0.0
              max_depth_quantile: 0.95
              ims_pattern: '{frame:06d}.png'
              prob: 1.0
            - dataset_name: "replica_niceslam"  # 8 real indoor scenes
              ratio: 1.0
              prob: 0.1
            - dataset_name: "tartanair"  # 369 indoor/outdoor scenes
              ratio: 1.0
              max_depth: 200 # meter unit, remove the sky
              min_depth_quantile: 0.0
              max_depth_quantile: 0.98
              ims_pattern: '{frame:06d}.png'
              prob: 1.0
            - dataset_name: "vkitti2"  # 50 synthetic driving scenes
              ratio: 1.0
              interp_using_t: True
              closest_using_t: True
              max_depth: 200 # meter unit, remove the sky
              min_depth_quantile: 0.0
              max_depth_quantile: 0.98
              ims_pattern: '{frame:05d}.jpg'
              mks_pattern: '{frame:05d}.png'
              dps_pattern: '{frame:05d}.exr'
              prob: 0.3
            # - ratio: 1.0 # point_odyssey/train
            # - ratio: 1.0 # point_odyssey/val
            - dataset_name: "ase"  # 100000 med-quality synthetic indoor scenes
              ratio: 1.0
              rot90: "clockwise"
              min_depth_quantile: 0.0
              max_depth_quantile: 0.99
              prob: 1.0
            - dataset_name: "adt"  # 233 indoor scenes
              ratio: 1.0
              rot90: "clockwise"
              min_depth_quantile: 0.0
              max_depth_quantile: 1.0
              interp_using_t: True
              closest_using_t: True
              prob: 0.5
            # Real-world datasets
            # - ratio: 1.0 # ARKitscenes
            #   min_depth_quantile: 0.02
            #   max_depth_quantile: 0.98
            #   dist_opt_K: True
            - dataset_name: "megadepth"  # 213 scenes
              ratio: 1.0
              min_depth_quantile: 0.02
              max_depth_quantile: 0.95
              prob: 0.5
            - dataset_name: "scannetpp"  # 229 scenes
              ratio: 1.0 # scannetpp
              min_depth_quantile: 0.02
              max_depth_quantile: 0.95
              prob: 1.0
            # - ratio: 1.0 # scannetpp_v2/nvs_sem_train
            #   min_depth_quantile: 0.02
            #   max_depth_quantile: 0.95
            #   dist_opt_K: True
            # - ratio: 1.0 # scannetpp_v2/nvs_sem_val
            #   min_depth_quantile: 0.02
            #   max_depth_quantile: 0.95
            #   dist_opt_K: True
            - dataset_name: "taskonomy"  # 530 scenes
              ratio: 1.0
              min_depth_quantile: 0.02
              max_depth_quantile: 0.95
              ims_pattern: '{frame:06d}.png'
              prob: 1.0
            - dataset_name: "wildrgbd/train"  # 4116 objects, some scenes may have different resolution
              ratio: 1.0
              min_depth_quantile: 0.02
              max_depth_quantile: 0.95
              prob: 1.0
            - dataset_name: "mapfree/train"  # 918 scenes
              ratio: 1.0
              min_depth_quantile: 0.02
              max_depth_quantile: 0.95
              use_masks: True
              masks_dir: masks
              prob: 1.25
            - dataset_name: "co3dv2/train"  # 28270 low-quality objects
              ratio: 1.0
              min_depth_quantile: 0.0
              max_depth_quantile: 0.98
              use_masks: True
              masks_dir: masks
              prob: 1.0
            - dataset_name: "mapillary/train"  # 74 driving scenes
              ratio: 1.0
              min_depth_quantile: 0.02
              max_depth_quantile: 0.95
              interp_using_t: True
              closest_using_t: True
              prob: 0.5
            - dataset_name: "mapillary/val"  # 36 driving scenes
              ratio: 1.0
              min_depth_quantile: 0.02
              max_depth_quantile: 0.95
              interp_using_t: True
              closest_using_t: True
              prob: 0.25
            - dataset_name: "dl3dv"  # 6370 scenes, already undistorted
              ratio: 1.0
              min_depth_quantile: 0.02
              max_depth_quantile: 0.95
              use_masks: True
              masks_dir: masks
              prob: 1.0
            - type: VGGTDataset  # NOTE this is the default config
              ddp_shard_dataset: False
              n_rays: -1
              max_size: 518 # use this to resize the image
              align_size: 14 # align the image to this size
              disk_dataset: True # to avoid loading all data into memory
              dist_opt_K: False # no distortion for synthetic data
              use_depths: True # use ground truth depths
              use_vhulls: False
              view_sample: [0, null, 1]
              frame_sample: [0, null, 1]
              source_type: DISTANCEROT
              # extra_src_pool: 24 # expand the source pool to twice the number of sources
              extra_src_pool_ratio: 1.0 # expand the source pool the same as the current number of sources
              aug_scale_ratio: 0.5 # probability of applying rescale augmentation
              min_depth_quantile: 0.0
              max_depth_quantile: 1.0
              scale_type: DIST
              portrait_check: False
              center_crop: True  # added by xiaoyang; MAKE fx==fy does not change and the optical center (cx, cy) is at the center of the image
              limit_max_aspect_ratio_as_original_ratio: True  # added by xiaoyang; limit the maximum aspect ratio as the original image ratio
              aug_scale: 0.3 # fov augmentation
              aug_image: True # image augmentation
              aug_image_cojit: True
              aug_image_cojit_ratio: 0.3 # 30% of the time, use individual image augmentation for each source
              n_srcs_list: &train_n_srcs_list [
                  1,
                  2,
                  3,
                  4,
                  5,
                  6,
                  7,
                  8,
                  9,
                  10,
                  11,
                  12,
                  13,
                  14,
                  15,
                  16,
                  17,
                  18,
                  19,
                  20,
                  21,
                  22,
                  23
              ]
              n_srcs_prob: &train_n_srcs_probs [
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0,
                  1.0
              ]
    sampler_cfg:
        type: SegmentProbabilitySampler
        fix_random: False  # avoid sampling problem after resuming training
        seed: 666  # not working if fix_random is True
    batch_sampler_cfg:  # config of class ImageBasedBatchSampler; NOTE that if this is set, the n_srcs_list and n_srcs_prob in the dataset_cfg will be ignored
        n_srcs_list: *train_n_srcs_list  # copied from dataset_cfg
        n_srcs_prob: *train_n_srcs_probs  # copied from dataset_cfg

val_dataloader_cfg:
    dataset_cfg:
        _delete_: True  # by default, the val config is copied from the train config, set _delete_ to True to override the default config
        type: MultiviewPointDataset
        split: VAL
        dataset_name: "hypersim/test"
        # data_root: /horizon-bucket/saturn_v_dev/users/tao02.xie/datasets/hypersim/train/ai_001_002/00 # train scene
        data_root: /horizon-bucket/saturn_v_dev/users/tao02.xie/datasets/hypersim/test/ai_001_010/00 # test scene
        n_rays: -1
        max_size: 518 # use this to resize the image
        align_size: 14 # align the image to this size
        view_sample: [0, null, 1]
        frame_sample: [0, null, 1]
        n_srcs_list: &val_n_srcs_list [7]
        n_srcs_prob: &val_n_srcs_probs [1.0]
        disk_dataset: True # to avoid loading all data into memory
        dist_opt_K: False # no distortion for synthetic data
        use_depths: True # use ground truth depths for evaluation
        source_type: DISTANCEROT
        use_world_coord: True
        min_depth_quantile: 0.0
        max_depth_quantile: 1.0
        scale_type: DIST
        portrait_check: True  # added by xiaoyang; to make it consistent with the training
        center_crop: True  # added by xiaoyang; to make it consistent with the training
        limit_max_aspect_ratio_as_original_ratio: True  # added by xiaoyang; to make it consistent with the training
    sampler_cfg:
        # by default, the val dataloader type is SequentialSampler (see base.yaml)
        type: DistributedSequentialSampler  # xiaoyang: a distributed sampler wrapper for SequentialSampler
        view_sample: [0, null, 1]  # use view_inds[0::1], see definition in datasamplers.py:get_inds; use more views for ddp_sharding
        frame_sample: [0, 1, 1]  # use frame_inds[0:1:1], see definition in datasamplers.py:get_inds
    batch_sampler_cfg:
        # by default, the val dataloader type is ImageBasedBatchSampler (see vggt.yaml)
        # by default, fix_random=True, aspect_ratio_range=-1 (see vggt.yaml)
        n_srcs_list: *val_n_srcs_list  # copied from dataset_cfg
        n_srcs_prob: *val_n_srcs_probs  # copied from dataset_cfg


# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
