# Configuration for ENeRF
configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/gfm.yaml # network model configuration
    - configs/datasets/game_synthetic/wukong/chapter2/250215_192858_463.yaml # dataset usage configuration

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
